openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://pengion-todo-a4f1355a880e.herokuapp.com'
paths:
  /api/v1/todos:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: status
          description: 'Filter by status.'
          example: pending
          required: false
          schema:
            type: string
            description: 'Filter by status.'
            example: pending
            nullable: false
        -
          in: query
          name: search
          description: 'Search by title or details.'
          example: null
          required: false
          schema:
            type: string
            description: 'Search by title or details.'
            example: null
            nullable: false
        -
          in: query
          name: sort_by
          description: 'Sort by field.'
          example: title
          required: false
          schema:
            type: string
            description: 'Sort by field.'
            example: title
            nullable: false
        -
          in: query
          name: sort_direction
          description: 'Sort direction.'
          example: asc
          required: false
          schema:
            type: string
            description: 'Sort direction.'
            example: asc
            nullable: false
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{"data":[{ "id": 13, "title": "Officia maiores fugiat quasi eligendi at.", "details": "Tempore velit qui magnam corrupti officiis occaecati. Quae dignissimos dolorem adipisci ab hic. Qui est maxime aut ut voluptatem autem aut. Minus laboriosam rem ducimus vero vero provident odio.", "status": "completed" }, { "id": 14, "title": "Nostrum et ea et dolore et in rerum.", "details": "Dolor consequatur dolore hic dolorem aut veniam. Ex amet voluptatem ipsa deleniti ut occaecati tempora recusandae. Consectetur beatae corrupti voluptates vel.", "status": "in progress" },]}'
      tags:
        - Todos
      security: []
    post:
      summary: 'Create a new todo item'
      operationId: createANewTodoItem
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 63
                    title: gym
                    details: 'up down, up down'
                    status: completed
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 63
                      title:
                        type: string
                        example: gym
                      details:
                        type: string
                        example: 'up down, up down'
                      status:
                        type: string
                        example: completed
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the todo.'
                  example: 'Buy groceries'
                  nullable: false
                details:
                  type: string
                  description: 'The details of the todo.'
                  example: 'Milk, Bread, Butter'
                  nullable: false
                status:
                  type: string
                  description: 'The status of the todo.'
                  example: pending
                  nullable: false
              required:
                - title
                - status
      security: []
  '/api/v1/todos/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 63
                    title: gym
                    details: 'up down, up down'
                    status: completed
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 63
                      title:
                        type: string
                        example: gym
                      details:
                        type: string
                        example: 'up down, up down'
                      status:
                        type: string
                        example: completed
      tags:
        - Todos
      security: []
    put:
      summary: 'Update the todo item'
      operationId: updateTheTodoItem
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 63
                    title: 'Updated title'
                    details: 'Updated details'
                    status: completed
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 63
                      title:
                        type: string
                        example: 'Updated title'
                      details:
                        type: string
                        example: 'Updated details'
                      status:
                        type: string
                        example: completed
      tags:
        - Todos
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the todo.'
                  example: 'Updated title'
                  nullable: false
                details:
                  type: string
                  description: 'The details of the todo.'
                  example: 'Updated details'
                  nullable: false
                status:
                  type: string
                  description: 'The status of the todo.'
                  example: completed
                  nullable: false
      security: []
    delete:
      summary: 'Remove the specified todo item.'
      operationId: removeTheSpecifiedTodoItem
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Todos
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the todo.'
        example: 63
        required: true
        schema:
          type: integer
tags:
  -
    name: Todos
    description: "\nAPIs for managing todos"
